### ISSUE TITLE
Practice to write issue

### ISSUE THREAD

**Issue by gracetrue** [gracetrue/open_test#1]
### Please write your name to this issue comments.

**Comment by luminous037** [comment]
엄지현

**Comment by mina-dong** [comment]
동민아

**Comment by LovellR** [comment]
이준호

**Comment by CoCo-1223** [comment]
김채은

**Comment by sinsohi** [comment]
신소희

**Comment by Pachyhead** [comment]
이종찬

1. git clone "주소"
2. git status
3. add index.js
4. git commit -m "index.js 수정"
5. git reset --hard HEAD~1
6. git add index.js
7. git commit -m "index.js 수정"
8. git push origin main
9. git log

**Comment by Kim-Juhyeong** [comment]
김주형

**Comment by GAUDUL** [comment]
임수현

**Comment by TaeWonM** [comment]
민태원
1. git clone https://github.com/kimcoding/test.git
2. git status
3. git add index.js
4. git commit -m "index.js 수정"
5. git reset --hard HEAD~1
6. git add index.js
7. git commit -m "index.js 수정"
8. git push origin main
9. git log

**Comment by sst7050** [comment]
심현석

**Comment by KimYeYoung125** [comment]
김예영

**Comment by Gorushi** [comment]
최윤서

**Comment by ayuuuneee** [comment]
김아윤

**Comment by semin-go** [comment]
고세민
1. git clone https://github.com/kimcoding/test.git
2. git status
3. git add index.js
4. git commit -m "index.js 수정"
5. git revert [commit hash]
6. git add index.js
7. git commit -m "index.js 수정"
8. git push origin main
9. git log

**Comment by minseonju** [comment]
민선주

**Comment by san-sae** [comment]
최유림

**Comment by JustHaWall** [comment]
김재민

**Comment by luminous037** [comment]
> 엄지현

1. git clone https://github.com/kimcoding/test.git
2. git status
3. git add index.js
4. git commit -m "index.js 수정"
5. git revert 해시
6. git add index.js
7. git commit -m "index.js 수정:
8. git push origin main
9. git log

**Comment by Kim-Juhyeong** [comment]
김주형
1. git clone https://github.com/kimcoding/test.git
2. git status
3. git add index.js
4. git commit -m "index.js 수정"
5. git reset --hard HEAD~1
6. git add index.js
7. git commit -m "index.js 수정"
8. git push origin main
9. git log

**Comment by sst7050** [comment]
1.git clone https://github.com/kimcoding/test.git
2.git status
3. git add index.js
4. git commit -m "index.js 수정"
5. git reset --hard HEAD~1
6. git add index.js
7. git commit 0m "index.js 수정"
8. git push origin main
9. git log

**Comment by CoCo-1223** [comment]
> 김채은
1. git clone https://github.com/kimcoding/test/git
2. git status
3. git add index.js
4. git commit -m "index.js 수정"
5. git reset HEAD^
6. git add index.js
7. git commit -m "index.js 수정"
8. git push origin main
9. git log

**Comment by minseonju** [comment]
> 민선주

민선주

1. git clone https://github.com/kimcoding/test.git
2. git status
3. git add index.js
4. git commit -m "index.js 수정"
5. git reset --hard HEAD~1
6. git add index.js
7. git commit -m "index.js 수정“
8. git push origin main
9. git log

**Comment by KimYeYoung125** [comment]
김예영
1. git clone https://github.com/kimcoding/test/git
2. git status
3. git add index.js
4. git commit -m 'index.js 수정'
5. git revert
6. git add index.js
7. git commit -m 'index.js 수정'
8. git push origin main
9. git log

**Comment by LovellR** [comment]
이준호

1 git clone https://github.com/kimcoding/test.git
2 git status
3 git add index.js
4 git commit -m "index.js 수정"
5 git reset --hard HEAD~1
6 git add index.js
7 git commit -m "index.js 수정"
8 git push origin main
9 git log

**Comment by GAUDUL** [comment]
1. git clone https://github.com/kimcoding/test.git
2. git status
3. git add index.js
4. git commit -m "index.js 수정"
5. git reset --hard HEAD~1
6. git add index.js
7. git commit -m "index.js 수정:
8. git push origin main
9. git log

**Comment by Gorushi** [comment]
1. git clone https://github.com/kimcoding/test.git
2. git status
3. git add index.js
4. git commit -m "index.js 수정"
5. git reset HEAD^
6. git add index.js
7. git commit -m "index.js 수정"
8. git push origin main
9. git log

**Comment by ayuuuneee** [comment]
김아윤

1. git clone https://github.com/kimcoding/test/git
2. git status
3. git add index.js
4. git commit -m "index.js 수정"
5. git reset --hard HEAD~1
6. git add index.js
7. git commit -m "index.js 수정"
8. git push origin main
9. git log

**Comment by san-sae** [comment]
최유림

1. git clone https://github.com/kimcoding/test.git
2. git status
3. git add index.js
4. git commit -m "index.js 수정"
5. git reset --hard HEAD~1
6. git add index.js
7. git commit -m "index.js 수정"
8. git push origin main
9. git log

**Comment by mina-dong** [comment]
> 동민아

1) git clone https://githu
2) git status
3) git add index.js
4) git commit -m "index.js 수정"
5) git reset --hard HEAD~1
6) git add index.js
7) git commit -m "index.js 수정"
8) git push origin main
9) git log

**Comment by wjdduqtls1517** [comment]
1. git clone https://github.com/kimcoding/test.git
2. git status
3. git add index.js
4. git commit -m "index.js 수정"
5. git reset --hard HEAD~1
6. git add index.js
7. git commit -m "index.js 수정"
8. git push origin main
9. git log
