### ISSUE TITLE
Practice to write issue and branch

### ISSUE THREAD

**Issue by gracetrue** [gracetrue/open_test#3]
Please write here your name and answer

**Comment by luminous037** [comment]
엄지현

**Comment by semin-go** [comment]
고세민
1. git checkout -b feat/signup
2. git branch
3. git branch-b feat/signup-oauth
4. git checkout feat/signup
5. git merge feat/signup-oauth
6. git push origin feat/signup
7. git stash
![image](https://github.com/gracetrue/open_test/assets/164436257/1a2bfb2f-240e-40e1-a01f-d232a8f58dc2)
![image](https://github.com/gracetrue/open_test/assets/164436257/0af396ea-4b60-481f-a0a1-6a892b99e38a)

**Comment by TaeWonM** [comment]
민태원
1. git checkout -b feat/signup
2. git branch -a 
3. git checkout -b feat/signup-oauth
4. git checkout feat/signup
5. git merge feat/signup-oauth
6. git push origin feat/signup
7. git stash

**Comment by temraire117** [comment]
이재협

**Comment by LovellR** [comment]
이준호

**Comment by Gorushi** [comment]
최윤서

**Comment by wjdduqtls1517** [comment]
임정엽

**Comment by Kim-Juhyeong** [comment]
김주형

**Comment by minseonju** [comment]
민선주

**Comment by JJW1223** [comment]
조진우
1. git checkout -b feat/signup
2. git branch
3. git checkout -b feat/signup-oauth
4. git checkout feat/signup
5. git merge feat/signup-oauth
6. git push origin feat/signup
7. git stash

![스크린샷 2024-05-10 123745](https://github.com/gracetrue/open_test/assets/85469701/3b550c65-3e88-415f-a018-c18222cbecc4)

CREATE DATABASE 'Mongoos'

use('Mongoos');db.createCollection('Collection',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "properties": {}
} }});

use('Mongoos');db.createCollection('address',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "description": "address",
  "required": [
    "street",
    "zip",
    "city",
    "country"
  ],
  "properties": {
    "zip": {
      "bsonType": "string"
    },
    "country": {
      "bsonType": "CHAR"
    },
    "city": {
      "bsonType": "string"
    },
    "street": {
      "bsonType": "string"
    }
  }
} }});

use('Mongoos');db.createCollection('customer',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "description": "customer info",
  "required": [
    "name",
    "surname"
  ],
  "properties": {
    "address": {
      "bsonType": "objectId"
    },
    "phone": {
      "bsonType": "object",
      "required": [
        "mobile"
      ],
      "properties": {
        "mobile": {
          "bsonType": "string"
        }
      }
    },
    "surname": {
      "bsonType": "string"
    },
    "name": {
      "bsonType": "string"
    }
  }
} }});

use('Mongoos');db.createCollection('order',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "description": "order",
  "required": [
    "date",
    "customer",
    "payment"
  ],
  "properties": {
    "date": {
      "bsonType": "date"
    },
    "address": {
      "bsonType": "string"
    },
    "payment": {
      "bsonType": "objectId"
    },
    "customer": {
      "bsonType": "objectId"
    }
  }
} }});

use('Mongoos');db.createCollection('payment',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "description": "payment",
  "required": [
    "name",
    "date",
    "code"
  ],
  "properties": {
    "date": {
      "bsonType": "date"
    },
    "code": {
      "bsonType": "string"
    },
    "name": {
      "bsonType": "string"
    }
  }
} }});

**Comment by sinsohi** [comment]
신소희

**Comment by KimYeYoung125** [comment]
김예영

**Comment by cOcOa-aa** [comment]
이규민

**Comment by gimbab2002** [comment]
김동균

**Comment by sst7050** [comment]
심현석

**Comment by rusia9217** [comment]
황유림

**Comment by GAUDUL** [comment]
임수현

**Comment by jeongseonwoong** [comment]
정선웅

**Comment by san-sae** [comment]
최유림

**Comment by cbnuleehyunwoo** [comment]
이현우

**Comment by mina-dong** [comment]
동민아

**Comment by YangHeeChang** [comment]
양희창

**Comment by CoCo-1223** [comment]
김채은
1.git checkout -b feat/signup
2.git branch
3.git checkout -b feat/signup-oauth
4.git checkout feat/signup
5.git merge feat/signup-oauth
6.git add .
   git commit -m" " 
   git push origin feat/signup
7.git stash

**Comment by ayuuuneee** [comment]
김아윤

**Comment by Pachyhead** [comment]
이종찬

1. git checkout -b "feat/signup"
2. git branch
3. git checkout -b "feat/signup-oauth"
4. git checkout feat/singup
5. git merge feat/signup-ouath
6. 커밋 후 > git push origin feat/signup
7. git stash save

**Comment by choigowon** [comment]
최고원

1. git checkout -b 'feat/signup'
2. git branch
3. git checkout -b 'feat/signup-oauth'
4. git checkout feat/signup
5. git merge feat/signup-oauth
6. git push origin feat/signup
7. git stash

![image](https://github.com/gracetrue/open_test/assets/154347680/7238c212-adf2-4837-bb11-e5cf6103e8a6)
![image](https://github.com/gracetrue/open_test/assets/154347680/85d7b8c9-9fbe-44e6-8395-a3c0591b468d)

**Comment by sst7050** [comment]
1. feat/signup 브랜치 생성 및 이동:
```
git checkout -b feat/signup
```

2. 브랜치 목록과 현재 브랜치 확인:
```
git branch
```

3. feat/signup-oauth 브랜치 생성:
```
git checkout -b feat/signup-oauth
```

4. feat/signup 브랜치로 이동:
```
git checkout feat/signup
```

5. feat/signup-oauth 브랜치의 내용을 feat/signup 브랜치로 병합:
```
git checkout feat/signup
git merge feat/signup-oauth
```

6. feat/signup 브랜치를 remote repository로 업로드:
```
git push origin feat/signup
```

7. 작업하던 코드를 다른 공간에 저장하는 방법:
- 작업중인 코드 변경사항을 커밋 후 원격 저장소에 푸시하여 백업
- 코드 변경사항을 다른 브랜치에 커밋하여 보관
- 변경사항을 스택이나 파일로 저장 후 필요할 때 다시 적용 (stash 사용)

**Comment by luminous037** [comment]
1. git checkout -b feat/signup
2. git branch
3. git checkout -b feat/signup-oauth
4. git checkout feat/signup
5. git merge feat/signup-oauth
6. git add. > git commit -m "업로드" > git push origin feat/signup-oauth
7. git stash

**Comment by jeongseonwoong** [comment]
1.git checkout -b feat/signup
2.git branch
3.git checkout -b feat/signup-oauth
4.git checkout feat/signup 
5.git merge feat/signup-oauth
6.git add . git commit -m"" git push origin feat/signup
7.git stash

**Comment by mina-dong** [comment]
> 동민아

1. git checkout -b feat/signup
2. git branch
3. git checkout -b feat/signup-oauth
4. git checkout feat/signup
5. git checkout feat/signup
   git merge feat/signup-oauth
6. git add .
   git commit -m "signup"
    git push feat/signup
7. git stash

**Comment by luminous037** [comment]
git checkout -b feat/signup
git branch
git checkout -b feat/signup-oauth
git checkout feat/signup
git merge feat/signup-oauth
git add. > git commit -m "업로드" > git push origin feat/signupgit stash

**Comment by cOcOa-aa** [comment]
1. git checkout -b feat/signup
2. git branch
3. git checkout -b feat/signup-oauth
4. git checkout feat/signup
5. git merge feat/signup-oauth
6. git add / git commit -m "" / git push origin feat/signup
7. git stash

**Comment by luminous037** [comment]
1. git checkout -b feat/signup
2. git branch
3. git checkout -b feat/signup-oauth
4. git checkout feat/signup
5. git merge feat/signup-oauth
6. git add. > git commit -m "업로드" > git push origin feat/signup-oauth
7. git stash

**Comment by cbnuleehyunwoo** [comment]
1. git checkout -b feat/signup
2. git branch, git status
3. feat/signup 브랜치에서 git checkout -b feat/signup-oauth
4. git checkout feat/signup
5. git merge feat/signup-oauth	
6. git push origin feat/signup
7. git stash로 저장하고 후에 git stash pop으로 불러온다.

**Comment by GAUDUL** [comment]
1. git checkout -b feat/signup
2. git branch
3. git chekcout -b feat/signup-oauth
4. git checkout feat/signup
5. git merge feat/signup-oauth
6. git push origin feat/signup
7. git stash

![image](https://github.com/gracetrue/open_test/assets/137772044/ffd0762b-22fe-4835-b58f-2168a36534c3)

CREATE DATABASE 'dada'

use('dada');db.createCollection('address',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "properties": {
    "zip": {
      "bsonType": "objectId"
    },
    "country": {
      "bsonType": "CHAR"
    },
    "city": {
      "bsonType": "objectId"
    },
    "street": {
      "bsonType": "objectId"
    }
  }
} }});

**Comment by temraire117** [comment]
1. git checkout feat/signup
2. git branch 
3. git branch feat/signup-oauth
4. git checkout feat/signup
5. git merge feat/signup-oauth
6. git add --all
git commit -m "text"
git push origin feat/signup
7. git stash

**Comment by minseonju** [comment]
1.git checkout -b feat/signup
2.git branch
3.git checkout -b feat/signup-oauth
4.git checkout feat/signup
5.git merge feat/signup-oauth
6.git add. > git commit -m "커밋메시지" > git push origin feat/signup-oauth
7.git stash

**Comment by luminous037** [comment]
1. git checkout -b feat/signup
2. git branch
3. git checkout -b feat/signup-oauth
4. git checkout feat/signup
5. git merge feat/signup-oauth
6. git add. > git commit -m "업로드" > git push origin feat/signup
7. git stash

**Comment by LovellR** [comment]
1. git checkout -b feat/signup
2. git branch
3. git branch feat/signup-oauth
4. git checkout feat/signup
5. git merge feat/signup-oauth
6. git add 
   git commit -m "메세지"
   git push origin feat/signup
7. git stash

**Comment by KimYeYoung125** [comment]
1. git checkout -b feat/signup
2. git branch
3. git checkout -b feat/signup-oauth
4. git checkout feat/signup
5. git merge feat/signup-oauth
6. git push origin feat/signup
7. git stash

**Comment by Gorushi** [comment]
1. git checkout -b feat/signup
2. git branch 
3. git checkout -b feat/signup-oauth
4. git checkout feat/signup
5. git merge feat/signup-oauth
6. git push origin feat/signup
7. git stash

**Comment by YangHeeChang** [comment]
1. git checkout -b "feat/signup"
2. git branch
3. git checkout -b "feat/signup-oauth"
4. git checkout feat/signup
5. git merge feat/signup-oauth
6. git push origin feat/signup
7. git stash

**Comment by san-sae** [comment]
최유림

1. git checkout -b feat/signup
2. git branch
3. git checkout -b feat/signup/oauth
4. git checkout feat/signup
5. merge feat/signup-oauth
6. git push origin feat/signup 
7. git stash 

![디비스키마사진](https://github.com/gracetrue/open_test/assets/97453758/bd140e4d-8cbd-4541-90de-4069650a6604)

```
CREATE DATABASE 'Mongoos'

use('Mongoos');db.createCollection('Collection',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "properties": {}
} }});

use('Mongoos');db.createCollection('address',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "description": "주소 설명",
  "required": [
    "street",
    "zip",
    "city",
    "country"
  ],
  "properties": {
    "zip": {
      "bsonType": "string"
    },
    "country": {
      "bsonType": "string"
    },
    "city": {
      "bsonType": "string"
    },
    "street": {
      "bsonType": "string"
    }
  }
} }});

use('Mongoos');db.createCollection('article',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "description": "상품 설명",
  "required": [
    "title",
    "price",
    "code"
  ],
  "properties": {
    "code": {
      "bsonType": "string"
    },
    "price": {
      "bsonType": "double"
    },
    "title": {
      "bsonType": "string"
    }
  }
} }});

use('Mongoos');db.createCollection('customer',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "description": "고객설명",
  "required": [
    "name",
    "surname",
    "address"
  ],
  "properties": {
    "address": {
      "bsonType": "objectId"
    },
    "phone": {
      "bsonType": "object",
      "properties": {
        "mobile": {
          "bsonType": "string"
        }
      }
    },
    "surname": {
      "bsonType": "string"
    },
    "name": {
      "bsonType": "string"
    }
  }
} }});

use('Mongoos');db.createCollection('order',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "description": "주문 설명",
  "required": [
    "date",
    "customer",
    "article"
  ],
  "properties": {
    "date": {
      "bsonType": "date"
    },
    "article": {
      "bsonType": "objectId"
    },
    "customer": {
      "bsonType": "objectId"
    }
  }
} }});
```

**Comment by gihong-free** [comment]
이기홍

**Comment by wjdduqtls1517** [comment]
1. git checkout -b feat/signup
2. git branch
3. git checkout -b feat/signup-oauth
4. git checkout feat/signup
5. git merge feat/signup-oauth
6. git push origin feat/signup
7. git stash

**Comment by gimbab2002** [comment]
1. git branch feat/signup
    git checkout feat/signup
2. git branch 
3. git branch feat/signup-oauth
    git checkout feat/signup-oauth
4. git checkout feat/signup
5. git merge feat/signup-oauth
6. git add 
    git commit
    git push origin feat/signup
7. git stash save

**Comment by Kim-Juhyeong** [comment]
1. git checkout -b feat/signup
2. git branch
3. git checkout -b feat/signup-oauth
4. git checkout feat/signup
5. git merge feat/signup-oauth
6. git push origin feat/signup
7. git stash

**Comment by gihong-free** [comment]
이기홍
git checkout -b "feat/signup"
git branch
git checkout -b "feat/signup-oauth"
git checkout feat/signup
git merge feat/signup-oauth
git push origin feat/signup
git stash

**Comment by rusia9217** [comment]
황유림
1. `git checkout -b feat/signup`
2. `git branch`
3. `git checkout -b feat/signup-oauth`
4. `git checkout feat/signup`
5. `git merge feat/signup-oauth`
6. `git add.` > `git commit -m "업로드"` >` git push origin feat/signup`
7. `git stash`

**Comment by sinsohi** [comment]
신소희
1. git checkout -b feat/signup
2. git branch
3. git checkout -b feat/signup/oauth
4. git checkout feat/signup
5. merge feat/signup-oauth
6. git add . -> git commit -m "commit message" -> git push origin feat/signup
7. git stash

**Comment by luminous037** [comment]
<img width="1512" alt="image" src="https://github.com/gracetrue/open_test/assets/135002121/73b209d8-6dde-41dc-83d2-7333f1bdae85">

**Comment by LovellR** [comment]
![1](https://github.com/gracetrue/open_test/assets/129665363/7127362b-e931-4c25-8191-e05611e5a83a)
CREATE DATABASE 'Mongo'

use('Mongo');db.createCollection('address',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "required": [
    "street",
    "zip",
    "city",
    "country"
  ],
  "properties": {
    "zip": {
      "bsonType": "string"
    },
    "country": {
      "bsonType": "CHAR"
    },
    "city": {
      "bsonType": "string"
    },
    "street": {
      "bsonType": "string"
    }
  }
} }});

use('Mongo');db.createCollection('customer',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "required": [
    "name",
    "surname"
  ],
  "properties": {
    "address": {
      "bsonType": "objectId"
    },
    "phone": {
      "bsonType": "object",
      "required": [
        "mobile"
      ],
      "properties": {
        "mobile": {
          "bsonType": "string"
        }
      }
    },
    "surname": {
      "bsonType": "string"
    },
    "name": {
      "bsonType": "string"
    }
  }
} }});

use('Mongo');db.createCollection('order',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "required": [
    "customer",
    "date",
    "payment",
    "address"
  ],
  "properties": {
    "date": {
      "bsonType": "date"
    },
    "address": {
      "bsonType": "string"
    },
    "payment": {
      "bsonType": "objectId"
    },
    "customer": {
      "bsonType": "objectId"
    }
  }
} }});

use('Mongo');db.createCollection('payment',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "required": [
    "name",
    "date",
    "code"
  ],
  "properties": {
    "date": {
      "bsonType": "date"
    },
    "code": {
      "bsonType": "objectId"
    },
    "name": {
      "bsonType": "string"
    }
  }
} }});

**Comment by cbnuLeehyunwoo** [comment]
![image](https://github.com/gracetrue/open_test/assets/85469621/05470b90-5108-4fc9-9a34-eca82e6295ab)

**Comment by luminous037** [comment]
<img width="1512" alt="image" src="https://github.com/gracetrue/open_test/assets/135002121/8825e41e-2d1a-4f37-adb1-4ed1bee1c8bd">
CREATE DATABASE 'Mongo'

use('Mongo');db.createCollection('Collection',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "required": [
    "title"
  ],
  "properties": {
    "title": {
      "bsonType": "string"
    }
  }
} }});

use('Mongo');db.createCollection('address',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "required": [
    "street",
    "zip",
    "city",
    "country"
  ],
  "properties": {
    "zip": {
      "bsonType": "string"
    },
    "country": {
      "bsonType": "string"
    },
    "city": {
      "bsonType": "string"
    },
    "street": {
      "bsonType": "string"
    }
  }
} }});

use('Mongo');db.createCollection('customer',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "description": "손님 정보",
  "required": [
    "Name",
    "surname",
    "address",
    "phone"
  ],
  "properties": {
    "address": {
      "bsonType": "objectId"
    },
    "phone": {
      "bsonType": "object",
      "required": [
        "mobile"
      ],
      "properties": {
        "mobile": {
          "bsonType": "string"
        }
      }
    },
    "surname": {
      "bsonType": "string"
    },
    "Name": {
      "bsonType": "string"
    }
  }
} }});

use('Mongo');db.createCollection('order',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "required": [
    "date",
    "customer",
    "payment",
    "address"
  ],
  "properties": {
    "date": {
      "bsonType": "date"
    },
    "address": {
      "bsonType": "string"
    },
    "payment": {
      "bsonType": "objectId"
    },
    "customer": {
      "bsonType": "objectId"
    }
  }
} }});

use('Mongo');db.createCollection('payment',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "required": [
    "name",
    "date",
    "code"
  ],
  "properties": {
    "date": {
      "bsonType": "double"
    },
    "code": {
      "bsonType": "string"
    },
    "name": {
      "bsonType": "string"
    }
  }
} }});

**Comment by cbnuleehyunwoo** [comment]
![image](https://github.com/gracetrue/open_test/assets/85469621/df814d36-1dc1-4a2e-8191-f993c74d363c)
CREATE DATABASE 'MongoDB_first'

use('MongoDB_first');db.createCollection('Collection',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "properties": {}
} }});

use('MongoDB_first');db.createCollection('address',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "description": "주소정보입니다",
  "required": [
    "street",
    "zip",
    "city",
    "country"
  ],
  "properties": {
    "zip": {
      "bsonType": "string"
    },
    "country": {
      "bsonType": "string"
    },
    "city": {
      "bsonType": "string"
    },
    "street": {
      "bsonType": "string"
    }
  }
} }});

use('MongoDB_first');db.createCollection('customer',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "required": [
    "name",
    "surname"
  ],
  "properties": {
    "address": {
      "bsonType": "objectId"
    },
    "phone": {
      "bsonType": "object",
      "required": [
        "mobile"
      ],
      "properties": {
        "mobile": {
          "bsonType": "string"
        }
      }
    },
    "surname": {
      "bsonType": "string"
    },
    "name": {
      "bsonType": "string"
    }
  }
} }});

use('MongoDB_first');db.createCollection('order',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "required": [
    "date",
    "customer",
    "article",
    "address"
  ],
  "properties": {
    "date": {
      "bsonType": "date"
    },
    "address": {
      "bsonType": "string"
    },
    "article": {
      "bsonType": "objectId"
    },
    "customer": {
      "bsonType": "objectId"
    }
  }
} }});

use('MongoDB_first');db.createCollection('payment',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "required": [
    "name",
    "date",
    "code"
  ],
  "properties": {
    "date": {
      "bsonType": "date"
    },
    "code": {
      "bsonType": "string"
    },
    "name": {
      "bsonType": "string"
    }
  }
} }});

**Comment by ImagoDei0212** [comment]
![Uploading 스크린샷 2024-05-10 123834.png…]()

**Comment by sst7050** [comment]
![캡처](https://github.com/gracetrue/open_test/assets/153179706/468c6266-a41e-4dd7-988b-273d514a4be2)
![캡처1](https://github.com/gracetrue/open_test/assets/153179706/79053a35-a1be-4d73-92fa-d47229efde63)

**Comment by cOcOa-aa** [comment]
![스크린샷 2024-05-10 123845](https://github.com/gracetrue/open_test/assets/85469644/04a1e65a-1d46-4408-b0eb-56d9aa12430b)

**Comment by YangHeeChang** [comment]
![스크린샷 2024-05-10 123912](https://github.com/gracetrue/open_test/assets/84493979/86c61a76-da5b-4a21-82a5-5e853f2b3839)
CREATE DATABASE 'Mongoos'

use('Mongoos');db.createCollection('address',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "required": [
    "street",
    "zip",
    "city",
    "country"
  ],
  "properties": {
    "zip": {
      "bsonType": "string"
    },
    "country": {
      "bsonType": "string"
    },
    "city": {
      "bsonType": "string"
    },
    "street": {
      "bsonType": "string"
    }
  }
} }});

use('Mongoos');db.createCollection('article',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "required": [
    "name",
    "date",
    "code"
  ],
  "properties": {
    "date": {
      "bsonType": "date"
    },
    "code": {
      "bsonType": "string"
    },
    "name": {
      "bsonType": "string"
    }
  }
} }});

use('Mongoos');db.createCollection('customer',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "required": [
    "name",
    "surname"
  ],
  "properties": {
    "address": {
      "bsonType": "objectId"
    },
    "phone": {
      "bsonType": "object",
      "required": [
        "mobile"
      ],
      "properties": {
        "mobile": {
          "bsonType": "string"
        }
      }
    },
    "surname": {
      "bsonType": "string"
    },
    "name": {
      "bsonType": "string"
    }
  }
} }});

use('Mongoos');db.createCollection('order',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "required": [
    "customer",
    "date",
    "payment"
  ],
  "properties": {
    "date": {
      "bsonType": "date"
    },
    "address": {
      "bsonType": "string"
    },
    "payment": {
      "bsonType": "objectId"
    },
    "customer": {
      "bsonType": "objectId"
    }
  }
} }});

**Comment by minseonju** [comment]
<img width="481" alt="스크린샷 2024-05-10 오후 12 38 48" src="https://github.com/gracetrue/open_test/assets/138373881/17b00622-5129-4024-8331-3c8b08038b8a">

**Comment by Kim-Juhyeong** [comment]
<img width="602" alt="스크린샷 2024-05-10 123834" src="https://github.com/gracetrue/open_test/assets/122871299/a59085b8-70e4-4b80-8dbc-c8b0803cdf18">

**Comment by Gorushi** [comment]
![1](https://github.com/gracetrue/open_test/assets/130200215/8ea1a235-8c12-4848-aef7-a4200cd82f5a)
![2](https://github.com/gracetrue/open_test/assets/130200215/5cd3faa4-63b7-4b02-bcd1-84a7599515c8)

**Comment by cOcOa-aa** [comment]
![스크린샷 2024-05-10 124001](https://github.com/gracetrue/open_test/assets/85469644/732a7da7-3355-49e9-a29f-1c5d52dd45dc)

**Comment by cOcOa-aa** [comment]
![스크린샷 2024-05-10 123845](https://github.com/gracetrue/open_test/assets/85469644/bf107187-5837-4311-ba96-16ce8fdc0d41)
![스크린샷 2024-05-10 124001](https://github.com/gracetrue/open_test/assets/85469644/89ad9c7f-09d3-4dd3-9748-4931661f703e)

**Comment by temraire117** [comment]
![스크린샷 2024-05-10 123958](https://github.com/gracetrue/open_test/assets/85469637/d5babd9e-824e-4cfb-b067-459fd7bc31a5)
![스크린샷 2024-05-10 124031](https://github.com/gracetrue/open_test/assets/85469637/746bcfa6-6f66-44e6-abe9-8df65a5d4193)

**Comment by TaeWonM** [comment]
![image](https://github.com/gracetrue/open_test/assets/129059512/c6cb76be-d0fe-4f64-9c70-5fdf9e3adbd8)
![image](https://github.com/gracetrue/open_test/assets/129059512/e28434ff-ca5c-4fcc-89b0-1ae76257015e)

**Comment by jeongseonwoong** [comment]
![image](https://github.com/gracetrue/open_test/assets/84301208/8b76adad-0fd6-483b-a138-96b2f3f25878)

**Comment by Pachyhead** [comment]
![image](https://github.com/gracetrue/open_test/assets/131434212/f9837436-1d3f-4a7e-939c-77d403c07357)

![image](https://github.com/gracetrue/open_test/assets/131434212/65b5de78-bb64-4844-be15-28e272b2e11a)

**Comment by jeongseonwoong** [comment]
CREATE DATABASE '실습'

use('실습');db.createCollection('adress',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "required": [
    "street",
    "zip",
    "city",
    "country"
  ],
  "properties": {
    "zip": {
      "bsonType": "string"
    },
    "country": {
      "bsonType": "string"
    },
    "city": {
      "bsonType": "string"
    },
    "street": {
      "bsonType": "string"
    }
  }
} }});

use('실습');db.createCollection('customer',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "required": [
    "name",
    "surname"
  ],
  "properties": {
    "address": {
      "bsonType": "objectId"
    },
    "phone": {
      "bsonType": "object",
      "required": [
        "mobile"
      ],
      "properties": {
        "mobile": {
          "bsonType": "string"
        }
      }
    },
    "surname": {
      "bsonType": "string"
    },
    "name": {
      "bsonType": "string"
    }
  }
} }});

use('실습');db.createCollection('order',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "required": [
    "customer",
    "date",
    "payment"
  ],
  "properties": {
    "date": {
      "bsonType": "date"
    },
    "address": {
      "bsonType": "string"
    },
    "payment": {
      "bsonType": "objectId"
    },
    "customer": {
      "bsonType": "objectId"
    }
  }
} }});

use('실습');db.createCollection('payment',{ validator: { $jsonSchema: {
  "bsonType": "object",
  "required": [
    "name",
    "date",
    "code"
  ],
  "properties": {
    "date": {
      "bsonType": "date"
    },
    "code": {
      "bsonType": "string"
    },
    "name": {
      "bsonType": "string"
    }
  }
} }});

**Comment by mina-dong** [comment]
![image](https://github.com/gracetrue/open_test/assets/82349462/8bf50c99-008f-46c7-940b-72ff8d70b5e8)
![image](https://github.com/gracetrue/open_test/assets/82349462/c88d9e1d-a358-40e3-809f-60525ae2fd2b)

**Comment by gimbab2002** [comment]
![image](https://github.com/gracetrue/open_test/assets/69901143/20d19427-8afc-426e-9436-30f668aa1d8e)
![image](https://github.com/gracetrue/open_test/assets/69901143/72ac1ab4-7286-4f6e-a12f-f694cda150ba)

**Comment by gihong-free** [comment]
![image](https://github.com/gracetrue/open_test/assets/81912071/1549077f-4cc9-482c-ac11-f776cc3e2af0)
