### ISSUE TITLE
Issue board for upload your answer - Week 11, 12

### ISSUE THREAD

**Issue by gracetrue** [gracetrue/open_test#5]
### Please write and upload your answer and figure.
---------------------------------------------------------------
### [24.05.17 실습 문제]

1. Git은 주로 어떠한 용도로 설계되었나요?
2. Git의 주요 목표는 무엇인가요?
3. Github는 git 외에 어떤 기능을 지원하나요?
4. 로컬 git 레포지토리에 새 파일을 추가하려면 어떻게 해야 하나요?
5. 로컬 git 레포지토리를 만드는 첫 번째 단계는 무엇인가요?
6. Git Bash가 무엇인가요?
7. Git에서 원격 레포지토리에서 가져올 때 merge conflicts가 발생하면 어떻게 해야 하나요?
8. Git 레포지토리와 파일 시스템 모두에서 파일을 제거하는데 사용되는 명령은 무엇인가요?

- 문제를 모두 풀고 다음 실습 시간 전까지 깃 이슈에 댓글을 달아주세요.

**Comment by TaeWonM** [comment]
민태원
 - 11주차
1. 형상관리를 위해 설계
2. 빠른 속도, 단순한 구조, 비선형적인 개발
3. star와 이슈트래킹 등의 기능을 제공한다.
4. git add
5. github에서 레포지토리를 열기
6. git에서 제공하는 shell 프로그램이다.
7. 충돌되는 부분을 찾아서 고친다.
8. git rm
 - 12주차
![image](https://github.com/gracetrue/open_test/assets/129059512/2007be62-2a59-4b26-be02-03da3b476d5c) ![image](https://github.com/gracetrue/open_test/assets/129059512/c7a7fae1-98da-44a9-97cf-6f149f770ff7)
git filter-branch --force --index-filter ‘git rm--cached --ignore-unmatch <파일 이름>’ --prune-empty HEAD
git push -force origin <브렌치 이름>

**Comment by LovellR** [comment]
이준호

**Comment by Gorushi** [comment]
최윤서

**Comment by semin-go** [comment]
고세민
1. 소스코드관리->프로그래머 간의 작업을 조정하고 소스 코드의 변경 사항 추적
2. 유연성, 데이터 무결성, 속도
3. 이슈 트래킹, 프로젝트 관리 etc
4. git add
5. git init
6.  GNU 프로젝트를 위한 유닉스 쉘->Window운영체제에서 GIt command line 환경을 제공하는 어플리케이션
7. 충돌이 발생한 파일을 수정한 후, merge ->진행하기 전에 수동으로 수정해서 conflicts 해결
8. git rm "file name"
![image](https://github.com/gracetrue/open_test/assets/164436257/414578db-4174-4324-a2bb-edb62ae2ca49)
![image](https://github.com/gracetrue/open_test/assets/164436257/a3851f08-b2d5-4a58-a498-719cf045d5fa)
git filter-branch --force --index-filter ‘git rm--cached --ignore-unmatch <파일 이름>’ --prune-empty HEAD
git push -force origin <브렌치 이름>

**Comment by Pachyhead** [comment]
이종찬

1. 분산형 버전 관리 시스템
2. 분산형 워크플로우 지원, 데이터 무결성 보장
3. 이슈 트래킹, 코드 리뷰, 협업 도구, 프로젝트 관리 등
4. git add <파일명> -> git commit
5. git init
6. 윈도우 환경에서 git을 사용하기 위한 터미널 프로그램
7. git status로 충돌이 발생한 파일을 확인 -> 해당 파일을 수동으로 수정 -> add, commit
8. git rm

**Comment by wjdduqtls1517** [comment]
임정엽

**Comment by choigowon** [comment]
최고원

1. 프로그래머 간의 작업을 조정하고 소스 코드의 변경 사항 추적하기 위해 설계
2. 데이터 무결성, 분산된 워크플로우 지원
3. web-based repository hosting service
4. git add
5. git init
6. cmd(윈도우), terminal(linux, mac)의 역할을 하며 다른 운영체제의 명령어 사용이 가능하다.
7. 진행하기 전에 수동으로 수정해서 conflicts 해결
8. git rm

**Comment by mina-dong** [comment]
동민아

**Comment by KimYeYoung125** [comment]
김예영

**Comment by CoCo-1223** [comment]
김채은
1. 파일 저장소 
2. 보안, 유연성, 버전 제어
3. 이슈 트래킹 
4. git add 
5. git init
7. GNU 프로젝트을 위한 유닉스 쉘
8. 충돌이 발생한 걸 변경한 후 add, commit, push 한다
9. git rm


![image](https://github.com/gracetrue/open_test/assets/136443156/6af4b311-0488-4a9e-a9d2-585d178c4faa)
filter-branch-force--index-filter'git rm --cached --ignore-unmatch[파일 경로명]'-prune-empty HEAD
git push -force origin [브랜치 이름]

**Comment by temraire117** [comment]
이재협

**Comment by jeongseonwoong** [comment]
정선웅

**Comment by luminous037** [comment]
엄지현

**Comment by Kim-Juhyeong** [comment]
김주형

**Comment by sst7050** [comment]
심현석

**Comment by GAUDUL** [comment]
임수현

1. 코드 관리 및 협업
2. 원활한 협업 및 효율적인 코드 관리와 다른 개발자들과의 코드 공유
3. 오픈소스 커뮤니티 조성
4. git add
5. git init
6. git에서 제공하는 shell 프로그램, git 명령어를 사용할 수 있는 환경 제공
7. 충돌이 일어난 부분을 직접 해결
8. git rm

![image](https://github.com/gracetrue/open_test/assets/137772044/2a2b83be-1691-41c5-b8f0-c7a0f03c2da5)



git filter-branch --force --index-filter ‘git rm--cached --ignore-unmatch [파일 경로명]’ --prune-empty HEAD
git push -force origin [브랜치명]

**Comment by cOcOa-aa** [comment]
이규민

**Comment by YangHeeChang** [comment]
양희창
1. 여러 개발자들이 프로젝트 진행 시 소스 코드의 효율적인 관리
2. 빠른 속도, 단순한 구조, 비선형적인 개발
3. 이슈 트래킹, 프로젝트 관리 도구, 팀 협업 기능 등을 지원
4. git add
5. git int
6. windows 환경에서 unix 스타일의 명령줄 인터페이스를 제공하는 도구, git 명령어를 포함하는 다양한 unix 명령어를 사용할 수 있게 함
7. 충돌이 발생한 파일 확인 후 수정
8. git rm

**Comment by minseonju** [comment]
민선주

**Comment by san-sae** [comment]
최유림

**Comment by cbnuleehyunwoo** [comment]
이현우
1. 소프트웨어 개발 프로젝트에서 코드 버전 관리와 협업을 위한 용도
2. 다양한 버전을 한번에 유연하게 관리
3.  코드 호스팅 및 버전 관리, 협업, 및 프로젝트 관리, 문서 공유 및 커뮤니티 기능
4. 로컬 레포지토리에서 파일에디터를 이용하여 파일 추가 
5. git init
6. Bash는 셀의 기능을 통해 GIt의 명령어를 사용할 수 있게 한다.
7. 충돌이 발생한 파일 확인, 충돌 발생 부분에서 어떠한 부분을 남기거나 지울것인지 결정 후 merge 수행
8. git rm

**Comment by cOcOa-aa** [comment]
1) 개발자들이 소스 코드의 버전을 관리하고 협업하는 과정에서 변경 사항을 추적하고, 여러 버전을 효율적으로 핸들링할 수 있도록 돕기 위함
2) 코드의 효율적인 관리, 데이터 무결성, 그리고 개발자 간의 고속 협업을 지원하는 것
3) 이슈 트래킹, 코드 리뷰, 프로젝트 관리, 위키, 사용자 간의 소셜 네트워킹 같은 기능들을 추가로 제공
4) git add [파일명]
5) git init
6) Bash 셸의 기능을 통합해 Git 명령을 사용할 수 있게 해줌
7) 충돌이 있는 파일을 열어 충돌을 해결하고, git add, git commit 으로 변경사항 추가 후 merge
8) git rm [파일명]

**Comment by sinsohi** [comment]
신소희
1. Git은 주로 소프트웨어 개발에서 버전 관리 시스템으로 설계되었다. 여러 개발자들이 협업할 때 코드의 변경 사항을 추적하고 관리하는데 사용된다.
2. Git의 주요 목표는 분산 버전 관리, 데이터 무결성, 비선형 워크플로우 지원 등이다.
3. GitHub는 Git 레포지토리 호스팅 외에도 이슈 트래킹, 프로젝트 관리, 코드 리뷰, 위키, 지속적 통합/배포(CI/CD) 등 다양한 기능을 지원한다.
4. git add 명령으로 파일을 스테이징 영역에 추가한 후, git commit 명령으로 변경 사항을 커밋한다.
5. git init 명령을 사용하여 현재 디렉토리를 Git 레포지토리로 초기화한다.
6. Git Bash는 Windows 환경에서 Unix 스타일의 명령줄 인터페이스를 제공하는 도구이다. Git 명령어를 실행할 수 있는 터미널 환경을 제공한다.
7. 충돌하는 파일을 수동으로 편집하여 충돌을 해결해야 한다. 그 후 git add 명령으로 수정된 파일을 스테이징하고 git commit 명령으로 병합 커밋을 생성한다.
8. git rm

**Comment by jeongseonwoong** [comment]
1. 코드 공유
2. 여러 개발자들이 코드를 공유할 수 있게 한다.
3. 이슈 트래킹: 프로젝트에서 발생하는 버그나 작업할 사항을 관리할 수 있는 이슈 트래커를 제공합니다. 이슈에 라벨을 붙이거나, 담당자를 지정하거나, 마일스톤을 설정할 수 있습니다.

프로젝트 관리: Kanban 스타일의 프로젝트 보드를 제공하여 작업 흐름을 시각적으로 관리할 수 있습니다. 이 보드를 통해 이슈와 풀 리퀘스트를 카드 형식으로 정리할 수 있습니다.

풀 리퀘스트(Pull Request): 코드 변경 사항을 리뷰하고 병합할 수 있는 기능을 제공합니다. 코드 리뷰 도구와 함께 변경 사항을 논의하고, 자동화된 테스트와 연동할 수 있습니다.

GitHub Actions: CI/CD(Continuous Integration/Continuous Deployment) 파이프라인을 구축할 수 있는 기능입니다. 워크플로우를 정의하여 코드를 빌드하고, 테스트하고, 배포할 수 있습니다.

GitHub Pages: 정적 웹사이트를 호스팅할 수 있는 기능입니다. 저장소의 특정 브랜치나 디렉토리에서 정적 파일을 제공하여 웹사이트를 생성할 수 있습니다.

패키지 관리: GitHub Packages를 통해 패키지를 호스팅하고 관리할 수 있습니다. npm, Maven, NuGet, Docker와 같은 다양한 패키지 레지스트리와 연동됩니다.

4. git add
6. git clone을 한다.
7. github를 bash shell을 이용하여 쉽게 사용할 수 있도록 만든 툴
8. 직접 코드의 conflict를 수정해줘야한다.
9. git rm

**Comment by luminous037** [comment]
1. 오픈소스를 업로드하는 플랫폼
2. 개발자들에게 효율적이고 안전한 협업 환경 제공
3. 커뮤니티 기능 
4. cat > 파일이름
5. 파일 생성 > 파일 오른쪽 클릭 후 git bash here 클릭 > git bash 터미널에서 git init
6. git 명령어를 사용할 수 있는 터미널
7. 코드의 충돌 부분을 수동으로 수정 후 merge
8. git rm

**Comment by sst7050** [comment]
1. [Git은 분산 버전 관리 시스템 (DVCS, Distributed Version Control System)으로, 여러 사람이 동시에 작업하는 프로젝트에서 중요한 파일의 변경사항을 추적하고 관리하는 데 사용됩니다.
2. [Git은 다음과 같은 목표를 가지고 설계되었습니다: 빠른 속도, 단순한 구조, 비선형적인 개발 (수천 개의 동시 다발적인 브랜치), 완벽한 분산, 그리고 대형 프로젝트에도 유용하게 (속도와 데이터 크기 면에서)]
3. [GitHub는 Git의 기능을 확장하여 협업을 촉진하고, 정책을 적용하고, 프로세스를 자동화하며, 작업의 가시성과 추적 가능성을 개선하여 팀의 생산성을 향상시킵니다.
4. [로컬 Git 레포지토리에 새 파일을 추가하려면 다음과 같은 단계를 따릅니다:
git init으로 Git 레포지토리를 초기화합니다.
git add . 명령어를 사용하여 업로드할 파일을 스테이징 영역에 추가합니다.
git commit -m "message" 명령어를 사용하여 스테이징 영역에 있는 변경 내용을 커밋으로 남깁니다.
5. 로컬 Git 레포지토리를 만드는 첫 번째 단계는 git init 명령을 실행하는 것입니다. [이 명령은 현재 디렉토리에 .git라는 하위 디렉토리를 생성하며, 이 디렉토리는 Git이 프로젝트의 메타데이터와 버전 정보를 저장하는 곳입니다.
6. [Git Bash는 Windows 운영 체제에서 Git 명령어를 실행할 수 있는 유닉스 스타일의 명령 줄 인터페이스입니다. Git Bash를 사용하면 Windows에서도 리눅스의 명령어를 사용할 수 있습니다.
7. Git에서 병합 충돌이 발생하면, 충돌이 발생한 파일을 열어 충돌 부분을 찾아 수정해야 합니다. [수정 후에는 git add 명령어를 사용하여 수정된 파일을 스테이징 영역에 추가하고, git commit 명령어를 사용하여 변경사항을 커밋합니다.
8. Git 레포지토리와 파일 시스템 모두에서 파일을 제거하는 데 사용되는 명령은 git rm입니다. [이 명령은 파일을 작업 디렉토리와 인덱스에서 모두 제거합니다.

**Comment by Kim-Juhyeong** [comment]
1. 버전 관리를 위해서 설계되었습니다.
2. 
3. 코파일럿, 코드스페이스, pages, discussions, advanced security
4. git add file
5. git clone
6. GNU 프로젝트를 위해 브라이언폭스가 작성한 유닉스 쉘입니다.
7. 충돌이 발생한 커밋을 삭제하거나, 내용을 수정
8. git rm

**Comment by Gorushi** [comment]
1. 소프트웨어 개발 프로젝트의 소스 코드 관리
2. 코드 변경 사항을 효율적으로 추적하고, 여러 버전의 코드를 안전하게 관리
3. 이슈 트래킹, 프로젝트 관리 등
4. git add
5.  git 저장소 만들 디렉토리로 이동 후 git init 
6. bash shell 의 기능을 통합해 git 명령 사용할 수 있도록 함
7. 병합 충돌 발생 시 충돌이 발생한 파일을 열어 직접 충돌 부분을 찾아 수정
8. git rm

**Comment by LovellR** [comment]
1 버전 관리 및 협업을 효율적으로 해 개발자들에게 개발의 편의성을 제공
2 버전관리, 데이터 무결성, 비선형 워크플로우 지원
3 이슈 트래킹, 리포지토리 호스팅, 통합, 배포, 프로젝트 관리 등의 기능
4 git add
5 git init
6 윈도우에서 git을 사용할 수 있게 해주는 터미널 애플리케이션
7 충돌확인 > 충돌 해결 > merge
8 git rm

**Comment by wjdduqtls1517** [comment]
1. 팀프로젝트를 효율적으로 관리
2. 분산 관리
3. 이슈 트래킹, 리뷰
4. git add
5. git init
6. Git 명령어 사용
7. 충돌 부분 찾아 해결
8. git rm

**Comment by minseonju** [comment]
1. 여러 개발자들이 협력하여 프로젝트를 개발하고 관리하는데 사용된다.
2. 코드를 분산 관리하기 위함이다.
3. 이슈 트래킹, 프로젝트 관리, 지속적 통합 배포 등 다양한 기능을 제공한다.
4. git add로 파일을 추가한 후 git commit으로 변경 사항을 커밋한다.
5. git init
6. Bash는 명령 인터페이스를 제공해준다.
7. 충돌을 일으키는 사항들을 수동으로 해결하고, 변경사항을 커밋해주어야한다.
8. git rm

**Comment by JJW1223** [comment]
조진우
1. Git은 분산 버전 제어 시스템으로서 프로젝트의 로컬 복제본이 완전한 버전 제어 리포지토리입니다. 이러한 모든 기능의 로컬 리포지토리 덕분에 오프라인으로 또는 원격으로 쉽게 작업할 수 있습니다.
2. 1) 빠른 속도  2) 단순한 구조  3) 비선형적 개발  4) 완벽한 분산  5) 대규모 프로젝트
3. 프로젝트, 버전, 브랜치, 커밋 관리
4. 파일을 만든 후 git add [파일이름]
5. git init
6. GNU 프로젝트를 위해 브라이언폭스가 작성한 유닉스 쉘이다. 1989년 발표되어 GNU 운영체제와 리눅스, 맥 OS X 그리고 다윈 등 운영 체제의 기본 쉘로 탑재되어 광범위하게 배포되었다. 최초의 유닉스 쉘 프로그램 인 sh의 확장판.
7. 병합 충돌 부분을 찾아서 수정한다
8. git rm

![image](https://github.com/gracetrue/open_test/assets/85469701/6c215c1e-ee0b-41e8-b2c4-3a8f164b9e46)

**Comment by mina-dong** [comment]
> 동민아

1.  형상관리도구로 협업시 주로 많이 사용된다.
2.  코드 버전 관리
3. 프로젝트 관리 등
4. git add
5.  git init
6.  git의 인터페이스 도구
7. 충돌되는 부분을 확인하고 해당되는 부분을 지우거나, 수정하는 등의 방법으로 충돌을 해결한다.
8.  git rm

**Comment by KimYeYoung125** [comment]
1. 프로젝트 개발 버전 관리 및 팀 프로젝트의 원활한 공동 작업
2. 소프트웨어 개발 프로세스 관리, 협업
3. 웹 기반 코드 호스팅, 이슈 트래킹, 보안 및 코드 검사 등을 지원함
4. 파일 생성 후 git add 파일명
5. git init
6. windows 운영체제에서 unix 스타일의 명령줄 인터페이스 제공함. git 명령어 사용할 수 있는 터미널 환경을 제공한다.
7. 충돌이 일어난 파일을 열어 수동으로 해결 후 병합한다.
8. git rm

**Comment by temraire117** [comment]
1. git은 버전 관리를 위해 설계되었고, 그 중에서도 VCS(분산신 버전 관리)이다.
2. git의 주요 목표는 빠른 속도, 단순한 구조, 비선형적 개발 지원, 완전한 분산, 대형 프로젝트의 유용한 다룸(속도와 크기에서) 이다.
3. git은 로컬에서만 동작 가능하다면 github는 이를 웹 상에 사용 가능하게 하여 다른 개발자와 공유 및 협업을 가능하게 한다.
4. git add, git commit
5. git clone
6. Windows 환경에서 git을 사용하기 위한 Unix 쉘
7. 충돌이 일어난 부분을 수정 
8. git rm

**Comment by san-sae** [comment]
최유림

1. 버전 관리 및 원활한 프로젝트 관리
2. 빠른 속도, 비선형적 개발 방식 지원, 분산
3. Git은 로컬 저장소에서 작동하는 반면  Github은 웹 상에서 클라우드 서버를 통해 로컬 저장소의 코드를 업로드하고 공유할 수 있어 다른 개발자와 작업을 공유하는 것을 가능하게 한다.
4. 파일 생성 > git add 파일명
5. git init
6. Git 을 이용할 수 있는 Bash(유닉스 쉘)
7. 충돌 부분을 수정한 뒤 다시 merge 시도
8. git rm

**Comment by gihong-free** [comment]
이기홍

소스코드, 형상관리
코드 정리, 유연성, 데이터 관리
이슈 트래킹, 프로젝트 관리, 협업 등
git add 파일명 -> git commit
git init
GNU 프로젝트를 위 유닉스 쉘
충돌이 발생한 파일->수정->commit
git rm

**Comment by sinsohi** [comment]
2023040036 신소희
![image](https://github.com/gracetrue/open_test/assets/136775478/badb4a43-fc90-49f6-ae02-65ba44c52c8e)

**Comment by gihong-free** [comment]
![스크린샷 2024-05-24 124009](https://github.com/gracetrue/open_test/assets/81912071/f27335fc-b172-4f35-91c8-ca1842826fe3)이기홍 2021040015

**Comment by mina-dong** [comment]
![image](https://github.com/gracetrue/open_test/assets/82349462/fd8d0930-e836-48cc-9dc3-6731e8a2a2f1)
동민아

**Comment by minseonju** [comment]
<img width="174" alt="스크린샷 2024-05-24 오후 12 29 53" src="https://github.com/gracetrue/open_test/assets/138373881/c39961bd-fdf3-4c43-b081-d2682832d26a">

**Comment by jeongseonwoong** [comment]
![image](https://github.com/gracetrue/open_test/assets/84301208/fb5e42ca-b212-4e78-b5ae-e51a2fd523c0)
정선웅

**Comment by cbnuleehyunwoo** [comment]
![image](https://github.com/gracetrue/open_test/assets/85469621/d9debb27-a231-4a59-a6bf-4262c1c12497)

**Comment by LovellR** [comment]
![1](https://github.com/gracetrue/open_test/assets/129665363/a6b172b4-38bb-42d9-bb3e-83747cfdc0e7)

**Comment by gimbab2002** [comment]
김동균
![image](https://github.com/gracetrue/open_test/assets/69901143/78c59de1-a099-4f69-b602-fbadd55a5089)

**Comment by cOcOa-aa** [comment]
![스크린샷 2024-05-24 123235](https://github.com/gracetrue/open_test/assets/85469644/e9d9456c-37fa-4dc7-826a-6cb058b3cc8e)

**Comment by choigowon** [comment]
최고원
![image](https://github.com/gracetrue/open_test/assets/154347680/0884eee9-bcf6-4827-bd91-ddd424e871e4)

git filter-branch --force \ --index-filter \ ‘git rm --cached --ignore-unmatch file’ \ --prune-empty HEAD
git push -force origin branch

**Comment by KimYeYoung125** [comment]
![김예영](https://github.com/gracetrue/open_test/assets/147297336/4e99e39c-cefd-4fe7-ba28-9c0e38dcbedc)

**Comment by Kim-Juhyeong** [comment]
<img width="161" alt="스크린샷 2024-05-24 123323" src="https://github.com/gracetrue/open_test/assets/122871299/d779031f-2b69-42b1-8b00-83f84f4626d3">

**Comment by san-sae** [comment]
2020022001 최유림
![image](https://github.com/gracetrue/open_test/assets/97453758/f225825e-18c1-4d6d-9d47-73e35fe4deeb)

**Comment by YangHeeChang** [comment]
![스크린샷 2024-05-24 123515](https://github.com/gracetrue/open_test/assets/84493979/56ba58e6-c0a1-4e2e-8272-5d96b708976b)

**Comment by Pachyhead** [comment]
이종찬 

<img src="https://github.com/gracetrue/open_test/assets/131434212/2ed237ef-cf3c-4f7b-8c6e-f4d9c5e480d6"  width="300">

git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch 파일명' --prune-empty HEAD

**Comment by mina-dong** [comment]
동민아
![image](https://github.com/gracetrue/open_test/assets/82349462/908c91ae-9de8-4460-95f7-c9f10623480a)

**Comment by temraire117** [comment]
git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch 파일명' --prune-empty HEAD
![스크린샷 2024-05-24 124358](https://github.com/gracetrue/open_test/assets/85469637/bcf4e831-cc9b-4ea6-b153-a2b9dfafff0f)

**Comment by luminous037** [comment]
<img width="259" alt="image" src="https://github.com/gracetrue/open_test/assets/135002121/90c707c9-fe8c-4e11-878a-180c3e0b6893">

**Comment by sst7050** [comment]
![캡처](https://github.com/gracetrue/open_test/assets/153179706/cd840c3c-0464-4a00-b02b-2ee0ca4e3ad1)

**Comment by cbnuleehyunwoo** [comment]
이현우
